# 评论通知
query commentNotificationQuery($page: Int) {
    notifications(type: GROUP_COMMENT, page: $page) {
        paginatorInfo {
            currentPage
            hasMorePages
        }
        data {
            id
            type
            time_ago
            article {
                id
                type
                body
                description
                created_at
                cover
                hits
                count_likes
                count_comments
                count_tips
                liked
                user {
                    avatar
                    name
                    id
                }
                category {
                    id
                    name
                    logo
                }
                images {
                    id
                    url
                    width
                    height
                }
                video {
                    id
                    url
                    duration
                    info {
                        width
                        height
                        rotate
                        covers
                    }
                    cover_url
                }
            }
            comment {
                id
                body
                lou
                created_at
                user {
                    id
                    avatar
                    name
                }
            }
            user {
                id
                name
                avatar
                followed_status
                gender
                age
                introduction
            }
        }
    }
}