#举报
# enum ReportType {
# articles（旧）
# comments
# users
# user
# post（新）
# }
mutation createReport($id: Int, $reason: String, $type: ReportType = post) {
    createReport(id: $id, reason: $reason, type: $type) {
        id
        reason
        created_at
        user {
            id
            name
        }
    }
}
