# 发布动态
# body:文字描述
# images:图片base64
# video_id:视频ID
# qcvod_fileid:腾讯云上传成功后的视频ID
# category_ids:分类IDs
# type:内容的类型
mutation createPostContent(
    $body: String!
    $images: [String!]
    $video_id: Int
    $qcvod_fileid: String
    $category_ids: [Int!]
) {
    createPostContent(
        body: $body
        images: $images
        video_id: $video_id
        qcvod_fileid: $qcvod_fileid
        category_ids: $category_ids
    ) {
        id
        spider {
            id
        }
        content
        description
        status
        liked
        count_likes
        count_comments
        review_id
        review_day
        is_ad
        created_at
        user {
            id
            name
            avatar
            gender
            age
            introduction
        }
        categories {
            id
            name
            logo
        }
        images {
            id
            url
            width
            height
        }
        video {
            id
            url
            cover
            duration
            width
            height
        }
    }
}