# 关注的用户动态
query followedArticlesQuery($page: Int, $user_id: Int!) {
    followedArticles(user_id: $user_id, count: 10, page: $page) {
        paginatorInfo {
            currentPage
            hasMorePages
        }
        data {
            id
            type
            body
            description
            time_ago
            cover
            hits
            count_likes
            count_comments
            count_tips
            liked
            user {
                avatar
                name
                id
                followed_status
            }
            categories {
                id
                name
                logo
            }
            images {
                id
                url
                width
                height
            }
            video {
                id
                url
                duration
                info {
                    width
                    height
                    rotate
                    covers
                }
                cover_url
            }
        }
    }
}