# 个人状态
query MeMetaQuery {
    me {
        id
        balance
        gold
        total_contributes
        today_contributes
        exchangeRate
        phone
        title_phone
        wallet {
            id
            type
            balance
            pay_account
            real_name
            total_withdraw_amount
            available_balance
            today_withdraw_left
            bind_platforms {
                alipay
                wechat
            }
            platforms {
                alipay
                wechat
            }
        }
        count_articles
        count_production
        count_likes
        count_follows
        count_followers
        count_followings
        count_favorites
    }
}