# 动态
query postsQuery($user_id: Int!, $count: Int, $page: Int) {
    posts(user_id: $user_id, count: $count, page: $page) {
        paginatorInfo {
            hasMorePages
            currentPage
        }
        data {
            id
            spider {
                id
            }
            content
            description
            status
            liked
            count_likes
            count_comments
            review_id
            review_day
            is_ad
            created_at
            user {
                id
                name
                avatar
                followed_status
                gender
                age
                introduction
            }
            categories {
                id
                name
                logo
            }
            images {
                id
                url
                width
                height
            }
            video {
                id
                url
                cover
                duration
                width
                height
            }
        }
    }
}