#视频列表（旧）
query recommendVideosQuery($page: Int, $count: Int) {
    recommendVideos(page: $page, count: $count) {
        paginatorInfo {
            hasMorePages
            currentPage
        }
        data {
            id
            body
            isAdPosition
            liked
            count_likes
            count_comments
            time_ago
            cover
            user {
                id
                name
                avatar
                followed_status
                gender
                age
                introduction
            }
            categories {
                id
                name
                logo
            }
            video {
                id
                url
                cover
                duration
                width
                height
            }
        }
    }
}