#找回密码
mutation retrievePasswordMutation($code: String!, $phone: String, $newPassword: String!) {
    retrievePassword(code: $code, phone: $phone, newPassword: $newPassword) {
        id
        name
        token
        phone
    }
}