mutation sendMessageMutation($user_id: Int!, $chat_id: Int!, $message: String!) {
    sendMessage(user_id: $user_id, chat_id: $chat_id, message: $message) {
        id
        message
        time_ago
        created_at
        user {
            id
            name
            avatar
        }
    }
}