# 黑名单列表
query showUserBlockQuery($user_id: Int!) {
    showUserBlock(user_id: $user_id, count: 5, page: 1) {
        paginatorInfo {
            currentPage
            hasMorePages
        }
        data {
            id
            name
            avatar
            count_articles
            count_likes
            introduction
            followed_status
        }
    }
}