# 登录功能
mutation signInMutation($account: String!, $password: String!, $uuid: String) {
    signIn(account: $account, password: $password, uuid: $uuid) {
        id
        name
        avatar
        token
        balance
        uuid
        title_phone
        gold
        wallet {
            id
            pay_account
            real_name
            bind_platforms {
                wechat
            }
        }
        birthday_msg
        gender
        phone
        introduction
        count_articles
        count_production
        count_likes
        count_follows
        count_followers
        count_followings
        count_favorites
        reward
        contribute
        exchangeRate
        doubleHighWithdrawCardsCount
        fiveTimesHighWithdrawCardsCount
        tenTimesHighWithdrawCardsCount
        threeYuanWithdrawBadgesCount
        fiveYuanWithdrawBadgesCount
        tenYuanWithdrawBadgesCount
        is_store
        lastest_certification {
            id
            remark
            status
        }
    }
}