# 用户主页
query userQuery($id: Int!) {
    user(id: $id) {
        id
        name
        avatar
        age
        gender
        background
        total_contributes
        today_contributes
        introduction
        count_articles
        count_likes
        count_followers
        count_followings
        count_favorites
        followed_status
    }
}