#签到记录
query CheckInsQuery($days: Int) {
    checkIns(days: $days) {
        today_checked
        keep_checkin_days
        checks {
            year
            date
            created_at
            checked
            gold_reward
            contribute_reward
            reward_rate
        }
    }
}
