# 发布动态
# body: 文字描述
# images: 图片base64
# video_id: 视频ID
# category_ids: 专题ID
# tag_names: 标签名
# qcvod_fileid: 腾讯云上传成功后的视频ID
# $share_link: 复制的视频分享链接
# type: 内容的类型
mutation createPostContent(
    $body: String!
    $images: [String!]
    $video_id: Int
    $qcvod_fileid: String
    $tag_names: [String]
    $share_link: String
) {
    createPostContent(
        body: $body
        images: $images
        video_id: $video_id
        qcvod_fileid: $qcvod_fileid
        tag_names: $tag_names
        share_link: $share_link
    ) {
        id
        spider {
            id
        }
        content
        description
        status
        liked
        count_likes
        count_comments
        review_id
        review_day
        is_ad
        created_at
        user {
            id
            name
            avatar
            gender
            age
            introduction
        }
        tags {
            data {
                id
                name
            }
        }
        images {
            id
            url
            width
            height
        }
        video {
            id
            url
            cover
            duration
            width
            height
        }
    }
}
