# 用户视频动态
query UserPostsQuery($user_id: Int!, $page: Int) {
  posts(user_id: $user_id, page: $page) {
    paginatorInfo {
      hasMorePages
      currentPage
    }
    data {
      id
      description
      content
      count_likes
      count_comments
      liked
      is_ad
      created_at
      spider {
        id
        created_at
        status
      }
      video {
        id
        width
        height
        url
        cover
        is_ad_video
      }
      user {
        id
        name
        avatar
        gender
        follow_users_count
        followers_count
        followed_user_status
        is_admin
        profile {
          sub_name
          birthday
          age
          introduction
        }
        level {
          id
          level
        }
      }
    }
  }
}
