go_production:
    stage: deploy
    script:
        - ssh root@hk008 "cd /data/www/neihan.sites && git pull"
        - ssh root@hk008 "cd /data/www/neihan.sites && bash ops/bash/env.sh"
        - ssh root@hk008 "cd /data/www/neihan.sites && bash ops/bash/pull.sh"
        - ssh root@hk008 "cd /data/www/neihan.sites && bash ops/bash/data.sh"
    only:
        - master
