go_production:
    stage: deploy
    script:
        - ssh root@hk008 "cd /data/www/neihan.sites && git pull && bash ops/bash/env.sh"
        - ssh root@hk008 "cd /data/www/neihan.sites && git pull && bash ops/bash/worker.sh web"
    only:
        - master
