#爬虫视频列表
query SpidersQuery($type: SpiderTypeEnum) {
  spiders(type: $type) {
    paginatorInfo {
      hasMorePages
      currentPage
    }
    data {
      id
      status
      source_url
      title
      reward
      remark
      video {
        id
        width
        height
        url
        cover
        is_ad_video
        count_likes
        created_at
        liked
        count_comments
        user {
          id
          name
          avatar
          followed_user_status
          profile {
            age
          }
          level {
            id
            level
          }
        }
      }
    }
  }
}
