query articleQuery($id: Int!) {
  article(id: $id) {
    id
    type
    body
    description
    body
    cover
    video_url
    time_ago
    hits
    liked_id
    favorited
    count_words
    count_likes
    count_tips
    count_replies
    count_comments
    user {
      id
      name
      avatar
      introduction
      count_articles
      count_likes
      followed_status
    }
    video {
      id
      info {
        height
        width
        rotate
      }
    }
    images {
      id
      url
      width
      height
    }
    collection {
      id
      name
    }
    category {
      id
      name
    }
    categories {
      id
      name
      logo
      count_articles
      count_follows
      followed
    }
    tips {
      id
      user {
        id
        name
        avatar
      }
    }
  }
}
