git submodule add http://code.haxibiao.cn/packages/haxibiao-store.git/ packages/haxibiao/store
git submodule add http://code.haxibiao.cn/packages/haxibiao-helpers.git/ packages/haxibiao/helpers
git submodule add http://code.haxibiao.cn/packages/haxibiao-task.git/ packages/haxibiao/task
git submodule add http://code.haxibiao.cn/packages/haxibiao-matomo.git/ packages/haxibiao/matomo
git submodule add http://code.haxibiao.cn/packages/haxibiao-content.git/ packages/haxibiao/content
git submodule add http://code.haxibiao.cn/packages/haxibiao-media.git/ packages/haxibiao/media
git submodule add http://code.haxibiao.cn/packages/haxibiao-base.git/ packages/haxibiao/base
git submodule add http://code.haxibiao.cn/packages/haxibiao-config.git/ packages/haxibiao/config
git submodule add http://code.haxibiao.cn/packages/haxibiao-live.git/ packages/haxibiao/live
