query collectionsQuery($user_id:Int!){
    collections(user_id:$user_id){
        data{
            id
            name
            logo
            type
            status
            count_articles
            count_follows
            followed
        }
    }
}