query collectionQuery
(
    $collection_id:Int!){
    collection(collection_id:$collection_id){
        id
        name
        logo
        type
        status
        count_articles
        count_follows
        followed
        posts{
            data{
                id
                content
            }
        }
    }

}