mutation editCollectionMutation(
    $collection_id:Int!
    $name: String!
    $logo: String
    $type:CollectType) {
    editCollection(collection_id:$collection_id,name: $name, logo: $logo,type:$type) {
        id
        name
        logo
        type
        status
        count_articles
        count_follows
        followed
    }
}