mutation moveOutCollectionsMutation
(
    $collection_id:Int!,
    $collectable_ids:[Int!]!
){
    moveOutCollections(
        collection_id:$collection_id,
        collectable_ids:$collectable_ids
    )

}