mutation moveInCollectionsMutation
(
    $collection_id:Int!,
    $collectable_ids:[Int!]!,
){
    moveInCollections(
        collection_id:$collection_id,
        collectable_ids:$collectable_ids
    )
}