# 搜索标签
query searchCollectionsQuery($query: String!, $page: Int, $count: Int) {
    searchCollections(query: $query, page: $page, count: $count) {
        paginatorInfo {
            hasMorePages
            currentPage
        }
        data {
            id
            name
            logo

        }
    }
}