# 收藏的文章
query favoritedArticlesQuery($user_id: Int!) {
  favorites(user_id: $user_id) {
    paginatorInfo {
      currentPage
      hasMorePages
    }
    data {
      id
      article {
        id
        type
        title
        description
        images {
          url
          thumbnail
        }
        cover
        time_ago
        user {
          id
          name
          avatar
        }
        hits
        count_likes
        count_replies
        count_tips
      }
    }
  }
}
