query issues($orderBy:[IssuesOrderByOrderByClause!]){
    issues(orderBy: $orderBy,count:10){
        paginatorInfo{
            hasMorePages
            currentPage
        }
        data{
            title
            background
            count_answers
            created_at
            updated_at
            id
        }
    }
}